In [1]:
import tensorflow as tf

2025-11-01 00:29:35.239749: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1761953375.258409    2836 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1761953375.264064    2836 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1761953375.278948    2836 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1761953375.278971    2836 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1761953375.278973    2836 computation_placer.cc:177] computation placer alr

In [2]:
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

I0000 00:00:1761953418.689365    2836 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6096 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2070 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 7.5


In [3]:
add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

print("add =", add.numpy())
print("sub =", sub.numpy())
print("mul =", mul.numpy())
print("div =", div.numpy())

add = 5
sub = -1
mul = 6
div = 0.6666666666666666


In [6]:
mean = tf.reduce_mean([a, b, c])
_sum = tf.reduce_sum([a, b, c])

print("mean =", mean.numpy())
print("sum =", _sum.numpy())

mean = 3
sum = 10


In [7]:
matrix1 = tf.constant(
    [
        [1., 2.],
        [3., 4.]
    ])
matrix2 = tf.constant(
    [
        [5., 6.],
        [7., 8.]
    ])

product = tf.matmul(matrix1, matrix2)

In [8]:
product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [9]:
product.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)